"""add_audit_log

Revision ID: 1c8dd033101a
Revises: c3d4e5f6a7b8
Create Date: 2026-04-04 11:26:02.816419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8dd033101a'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_model', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_user_timestamp', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_model'), ['target_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('achievement_types', schema=None) as batch_op:
        batch_op.drop_index('ix_achievement_types_code')
        batch_op.create_index(batch_op.f('ix_achievement_types_code'), ['code'], unique=True)

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_users_username')
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_index('ix_leagues_code')
        batch_op.create_index(batch_op.f('ix_leagues_code'), ['code'], unique=True)

    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_index('ix_managers_name')
        batch_op.create_index(batch_op.f('ix_managers_name'), ['name'], unique=True)

    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index('ix_seasons_code')
        batch_op.create_index(batch_op.f('ix_seasons_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_code'))
        batch_op.create_index('ix_seasons_code', ['code'], unique=False)

    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managers_name'))
        batch_op.create_index('ix_managers_name', ['name'], unique=False)

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leagues_code'))
        batch_op.create_index('ix_leagues_code', ['code'], unique=False)

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))
        batch_op.create_index('ix_admin_users_username', ['username'], unique=False)

    with op.batch_alter_table('achievement_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievement_types_code'))
        batch_op.create_index('ix_achievement_types_code', ['code'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_model'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('idx_audit_user_timestamp')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
