"""remove_obsolete_match_model

Revision ID: 9a30d278d31d
Revises: 58667e02fd0d
Create Date: 2026-04-23 12:09:57.498743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a30d278d31d'
down_revision: Union[str, None] = '58667e02fd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_away_team_id'))
        batch_op.drop_index(batch_op.f('ix_matches_home_team_id'))
        batch_op.drop_index(batch_op.f('ix_matches_season_id'))

    op.drop_table('matches')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('home_team_id', sa.INTEGER(), nullable=False),
    sa.Column('away_team_id', sa.INTEGER(), nullable=False),
    sa.Column('season_id', sa.INTEGER(), nullable=False),
    sa.Column('home_score', sa.INTEGER(), nullable=False),
    sa.Column('away_score', sa.INTEGER(), nullable=False),
    sa.Column('performed_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['managers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['managers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_home_team_id'), ['home_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_away_team_id'), ['away_team_id'], unique=False)

    # ### end Alembic commands ###
