"""Add unique constraint on achievements (manager_id, league, season, achievement_type)

Revision ID: a1b2c3d4e5f6
Revises: 4349a74b0533
Create Date: 2026-04-03 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '4349a74b0533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove potential duplicates before adding constraint
    # Delete duplicate achievements, keeping the one with the lowest id
    op.execute("""
        DELETE FROM achievements
        WHERE id NOT IN (
            SELECT MIN(id)
            FROM achievements
            GROUP BY manager_id, league, season, achievement_type
        )
    """)

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            'uq_achievement_manager_league_season_type',
            ['manager_id', 'league', 'season', 'achievement_type']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_constraint('uq_achievement_manager_league_season_type', type_='unique')

    # ### end Alembic commands ###
