"""upgrade_achievement_schema

Revision ID: c8a1f0cd030d
Revises: 1c8dd033101a
Create Date: 2026-04-08 17:45:08.596130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a1f0cd030d'
down_revision: Union[str, None] = '1c8dd033101a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('league_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('season_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_points', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('multiplier', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_points', sa.Float(), nullable=True))
        batch_op.drop_index('ix_achievements_achievement_type')
        batch_op.drop_index('ix_achievements_league')
        batch_op.drop_index('ix_achievements_season')
        batch_op.drop_constraint('uq_achievement_manager_league_season_type', type_='unique')
        batch_op.create_unique_constraint('uq_achievement_manager_league_season_type', ['manager_id', 'type_id', 'league_id', 'season_id'])
        batch_op.create_index(batch_op.f('ix_achievements_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievements_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievements_type_id'), ['type_id'], unique=False)
        batch_op.create_foreign_key('fk_achievements_season_id', 'seasons', ['season_id'], ['id'])
        batch_op.create_foreign_key('fk_achievements_type_id', 'achievement_types', ['type_id'], ['id'])
        batch_op.create_foreign_key('fk_achievements_league_id', 'leagues', ['league_id'], ['id'])
        batch_op.drop_column('league')
        batch_op.drop_column('achievement_type')
        batch_op.drop_column('season')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('achievement_type', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('league', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_achievements_type_id'))
        batch_op.drop_index(batch_op.f('ix_achievements_season_id'))
        batch_op.drop_index(batch_op.f('ix_achievements_league_id'))
        batch_op.drop_constraint('uq_achievement_manager_league_season_type', type_='unique')
        batch_op.create_unique_constraint('uq_achievement_manager_league_season_type', ['manager_id', 'league', 'season', 'achievement_type'])
        batch_op.create_index('ix_achievements_season', ['season'], unique=False)
        batch_op.create_index('ix_achievements_league', ['league'], unique=False)
        batch_op.create_index('ix_achievements_achievement_type', ['achievement_type'], unique=False)
        batch_op.drop_column('final_points')
        batch_op.drop_column('multiplier')
        batch_op.drop_column('base_points')
        batch_op.drop_column('season_id')
        batch_op.drop_column('league_id')
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
