"""Initial schema: countries, managers, achievements tables

Revision ID: d65f2c57c0a9
Revises: 
Create Date: 2026-03-29 17:32:20.424073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65f2c57c0a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('flag_path', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_code'), ['code'], unique=True)

    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managers_name'), ['name'], unique=False)

    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achievement_type', sa.String(length=20), nullable=False),
    sa.Column('league', sa.String(length=10), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('icon_path', sa.String(length=100), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_achievement_type'), ['achievement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievements_league'), ['league'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievements_manager_id'), ['manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievements_season'), ['season'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_season'))
        batch_op.drop_index(batch_op.f('ix_achievements_manager_id'))
        batch_op.drop_index(batch_op.f('ix_achievements_league'))
        batch_op.drop_index(batch_op.f('ix_achievements_achievement_type'))

    op.drop_table('achievements')
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managers_name'))

    op.drop_table('managers')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_code'))

    op.drop_table('countries')
    # ### end Alembic commands ###
